workflows:
  ios-debug-workflow:
    name: iOS Debug Workflow
    environment:
      xcode: latest
      flutter: stable
    scripts:
      - name: Fetch dependencies
        script: |
          flutter pub get
      - name: Build iOS Debug for Device
        script: |
          flutter build ios --debug --no-codesign
    artifacts:
      - build/ios/iphoneos/*.app
